name: test

on:
  workflow_dispatch:

jobs:
  sdk-go:
    name: "core integration"
    runs-on: dagger-runner
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "sipsma/dagger"
          ref: "tests"
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: go test -v -run TestContainer $(pwd)/core/integration/
      - run: apt-get install -y fio && fio --name TEST --eta-newline=5s --filename=temp.file --rw=randrw --size=2g --io_size=10g --blocksize=4k --ioengine=libaio --fsync=1 --iodepth=1 --direct=1 --numjobs=1 --runtime=60 --group_reporting
