name: test

on:
  push:
    branches: ["main"]
  pull_request:
  # Enable manual trigger for easy debugging
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
  workflow_dispatch:

jobs:
  sdk-go:
    name: "sdk / go"
    runs-on: dagger-runner
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "dagger/dagger"
          ref: "v0.3.9"
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: cd sdk/go && go test -v ./...
