name: test

on:
  workflow_dispatch:

jobs:
  sdk-go:
    name: "sdk / go"
    runs-on: dagger-runner
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "sipsma/dagger"
          ref: "tests"
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: go test -v -run TestContainer $(pwd)/core/integration/
